### ISSUE TITLE
trouble converting map

### ISSUE THREAD

**Issue by maksw2** [MaximumADHD/Roblox-File-Format#22]
![image](https://github.com/MaximumADHD/Roblox-File-Format/assets/66273956/b73fcce7-01da-4cc8-bcff-7e073b2f2b07)

**Comment by GrowtopiaJe** [comment]
You trying to use source2rblx, its no longer maintained, nobody gonna help you with that
![image](https://github.com/MaximumADHD/Roblox-File-Format/assets/41511885/ef6f23f6-d448-467c-8c8f-aceb97793f1f)

**Comment by maksw2** [comment]
all i need is a compiled and working binary.

**Comment by GrowtopiaJe** [comment]
> all i need is a compiled and working binary.

This is Github, you have to do everything by self, you've been given tools and raw project, do the stuff. If you can't compile, that's not author of project fault, he said that "No longer maintained", means it won't work either, it worked in old versions of roblox

**Comment by maksw2** [comment]
"No longer maintained" doesn't mean it doesn't work, but it might not work. And GitHub supports a thing called a release. Also, i had an old project from about a year ago and it loaded just fine.

**Comment by maksw2** [comment]
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at RobloxFiles.DataTypes.CFrame.op_Multiply(CFrame a, CFrame b)
   at Extensions.PivotTo(PVInstance pv, CFrame cf) in C:\Users\maksw\Documents\s2r\Source2Roblox-main\Util\Extensions.cs:line 238
   at Source2Roblox.Geometry.MeshBuilder.BakeBSP_RBXL(BSPFile bsp, GameMount game) in C:\Users\maksw\Documents\s2r\Source2Roblox-main\Geometry\MeshBuilder.cs:line 1191
   at Source2Roblox.Program.Main(String[] args) in C:\Users\maksw\Documents\s2r\Source2Roblox-main\Program.cs:line 206
